"""Add role column to users table

Revision ID: 5b7329545c52
Revises: 
Create Date: 2024-02-28 17:45:19.109796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5b7329545c52'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peminjaman')
    op.drop_table('ulasanbuku')
    op.drop_table('koleksipribadi')
    op.drop_table('buku')
    op.drop_index('namakategori', table_name='kategoribuku')
    op.drop_table('kategoribuku')
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'petugas', 'peminjam'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.create_table('kategoribuku',
    sa.Column('kategori_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('namakategori', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('kategori_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('namakategori', 'kategoribuku', ['namakategori'], unique=True)
    op.create_table('buku',
    sa.Column('id_buku', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('judul', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('penulis', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('penerbit', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('tahunterbit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('kategori_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategoribuku.kategori_id'], name='buku_ibfk_1'),
    sa.PrimaryKeyConstraint('id_buku'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('koleksipribadi',
    sa.Column('koleksi_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('buku_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['buku_id'], ['buku.id_buku'], name='koleksipribadi_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id_user'], name='koleksipribadi_ibfk_1'),
    sa.PrimaryKeyConstraint('koleksi_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ulasanbuku',
    sa.Column('id_ulasan', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_buku', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('ulasan', mysql.TEXT(), nullable=False),
    sa.Column('rating', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_buku'], ['buku.id_buku'], name='ulasanbuku_ibfk_2'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], name='ulasanbuku_ibfk_1'),
    sa.PrimaryKeyConstraint('id_ulasan'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('peminjaman',
    sa.Column('id_peminjaman', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_buku', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tanggalpeminjaman', sa.DATE(), nullable=False),
    sa.Column('tanggalpengembalian', sa.DATE(), nullable=True),
    sa.Column('statuspeminjaman', mysql.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_buku'], ['buku.id_buku'], name='peminjaman_ibfk_2'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], name='peminjaman_ibfk_1'),
    sa.PrimaryKeyConstraint('id_peminjaman'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
